const formFields = [
  {
    tag: "input",
    type: "radio",
    name: "isMentor",
    "cf-questions": "Signing up as a mentor?",
    "cf-label": "Yes",
    value: "Yes",
  },
  {
    tag: "input",
    type: "radio",
    name: "isMentor",
    "cf-label": "No",
    value: "No",
  },
  {
    tag: "input",
    type: "checkbox",
    name: "interests",
    "cf-questions": "What are your Interests?",
    "cf-label": "Technology",
    value: "Technology",
  },
  {
    tag: "input",
    type: "checkbox",
    name: "interests",
    "cf-label": "Entrepreneurship",
    value: "Enterpreneurship",
  },
  {
    tag: "input",
    type: "checkbox",
    name: "interests",
    "cf-label": "Marketing",
    value: "Marketing",
  },
  {
    tag: "input",
    type: "checkbox",
    name: "interests",
    "cf-label": "Designing",
    value: "Designing",
  },
  {
    tag: "input",
    type: "checkbox",
    name: "interests",
    "cf-label": "Other",
    value: "Other",
  },
  {
    tag: "input",
    type: "checkbox",
    name: "expertise",
    "cf-questions": "What is your Area of Expertise?",
    "cf-label": "Programming",
    value: "Programming",
  },
  {
    tag: "input",
    type: "checkbox",
    name: "expertise",
    "cf-label": "Software Development",
    value: "Software Development",
  },
  {
    tag: "input",
    type: "checkbox",
    name: "expertise",
    "cf-label": "Marketing",
    value: "Marketing",
  },
  {
    tag: "input",
    type: "checkbox",
    name: "expertise",
    "cf-label": "UI & UX",
    value: "UI & UX",
  },
];

export default formFields;
